# 主页标题和介绍
index:
  name: "小吴博客" # 博主 / 站点的名称
  slogan: "记录小吴学习路上的点点滴滴" # Slogan



global:
  # 网页访问统计
  web_analytics:
    busuanzi:
      enable: true
      # 页面显示的文本，{} 是数字的占位符（必须包含），下同
      pv_format: "总访问量 {} 次"
      uv_format: "总访客数 {} 人"
  # 页面字体
  font:
    family: "'Noto Sans SC', sans-serif"
    # 字体 CSS 文件，选填。注意，字体 CSS 文件不是字体文件，而是像 Google Fonts 一样声明字体的文件。
    css: "https://fonts.googleapis.com/css2?family=Noto+Sans+SC&display=swap"




# 配置顶导航栏
navbar:
  menu:
		# 导航栏文本: 导航栏链接
    首页: /
    归档: /archives
    分类: /categories
    标签: /tags 
    GitHub: https://github.com



post:
  # 启用文章字数统计与时长预计。
  wordcount:
    enable: true # 设为 True。
    min2read:
      enable: true # 设为 True。
      # 每分钟阅读多少字，如果是技术文章，建议降低
      words: 120
  # 是否开启评论
  comment: false
  # 阅读进度分享
  readingProgess:
		enable: true
  # 文章打赏
  donate:
    enable: true
    # 打赏文字
    text: "喜欢这篇文章？快来加群和作者一起学习"
    # 方式
    way:
			# 打赏方式文字:打赏链接
      加群: "http://qm.qq.com/cgi-bin/qm/qr?_wv=1027&k=M0tzsMGoPFbMnHGCo0LqD2Od08tyCfAi&authKey=hr7ni%2FOrR40loa1PScMZoQEaRI4uVOMQDHIj%2BmYjfQDNywX9tGC6jqsX3yqmjAZa&noverify=0&group_code=781518182"
  # 文章版权
  copyright:
    enable: true
    authorURL: /
    content: '本博客所有文章除特别声明外，均采用 <a href="https://creativecommons.org/licenses/by-sa/4.0/deed.zh" rel="nofollow noopener">CC BY-SA 4.0 协议</a> ，转载请注明出处，谢谢。'
    # CC 版权协议，显示 CC 版权的 SVG
    cc: true
    # 复制内容时追加版权
    clipboard: 
      enable: false
      content: ''



# 站内搜索
search:
  enable: true
  # post 为文章，page 为页面，all 为所有
	field: post